default: &default
  adapter: postgresql
  encoding: unicode
  host: ec2-52-4-111-46.compute-1.amazonaws.com
  database: d40skhdtgco391
  pool: 5
  port: 5432
  username: pvjnttmmtxhtpt
  password: becae3eec189b51db476670296fd26f1f7dee4643d6eb814e0673f0e81181d6f

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default